alasdair-macleod/DemoAppFront

.travis.yml

still fiddiling with .travis.yml

VER3-137 Fix .travis.yml

---

src/app/app.component.html
src/app/flask.component.html
src/app/flask.directive.ts
src/index.html

re adding mathJax via CDN.. ugh

VER3 138 remove math jax

---

src/app/app.component.html
src/app/app.component.spec.ts
src/app/flask.component.html
src/app/flask.component.ts
src/app/flask.directive.ts

adding back mathjax. going to have to be very careful abot tests involving this...

VER3-138 remove math jax

---

src/app/correlation-matrix/correlation-matrix.component.ts
src/app/shared/RepeatedMeasure.ts
src/app/shared/WithinISUFactors.ts
src/app/shared/constants.ts
src/app/shared/navigation.service.ts
src/app/shared/study-design.ts
src/app/shared/study.service.ts
src/app/solve-for/solve-for.component.html
src/app/solve-for/solve-for.component.ts
src/app/statistical-tests/statistical-tests.component.spec.ts
src/app/statistical-tests/statistical-tests.component.ts
src/app/study-form/study-form.component.html
src/app/study-form/study-form.component.ts
src/app/type-one-error/type-one-error.component.html
src/app/type-one-error/type-one-error.component.ts
src/app/user-mode/user-mode.component.ts
src/app/within-isu-clusters/within-isu-clusters.component.html
src/app/within-isu-clusters/within-isu-clusters.component.spec.ts
src/app/within-isu-clusters/within-isu-clusters.component.ts
src/app/within-isu-outcomes/within-isu-outcomes.component.ts
src/app/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/within-isu-repeated-measures/within-isu-repeated-measures.component.spec.ts
src/app/within-isu-repeated-measures/within-isu-repeated-measures.component.ts

TIDY UP ARCHITECHTURE AND IMPROVE TEST COVERAGE

Ver3 218 consolidate

---

src/app/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/within-isu-repeated-measures/within-isu-repeated-measures.component.ts

added auto fill option for repeated measures

Ver3 193 spacing

---

src/app/shared/WithinISUFactors.ts
src/app/shared/study-design.ts
src/app/shared/study.service.ts
src/app/solve-for/solve-for.component.ts
src/app/statistical-tests/statistical-tests.component.ts
src/app/target-event/target-event.component.ts
src/app/type-one-error/type-one-error.component.ts
src/app/within-isu-clusters/within-isu-clusters.component.ts
src/app/within-isu-outcomes/within-isu-outcomes.component.ts
src/app/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/within-isu-repeated-measures/within-isu-repeated-measures.component.ts

finish adding all input to study design

VER3-193 finish adding all input to study design

---

package.json
src/app/app.module.ts
src/app/shared/constants.ts
src/app/statistical-tests/statistical-tests.component.spec.ts
src/app/study-form/study-form.component.html

VER3-177 fix test

---

src/app/study-form/hypothesis-within/hypothesis-within.component.ts

fix travis build by hiding kron function

VER3-237 hide kron

---

src/app/shared/PartialMatrix.ts
src/app/shared/PowerCurve.ts
src/app/shared/PowerCurveDataSeries.ts
src/app/study-form/hypothesis-within/hypothesis-within.component.ts
src/app/study-form/optional-specs-power-curve-data-series/optional-specs-power-curve-data-series.component.html
src/app/study-form/optional-specs-power-curve-data-series/optional-specs-power-curve-data-series.component.ts

added power curve data series component

Ver3 280 power curve data seies

---

package.json
src/app/mathjax/mathjax.component.ts
src/app/shared/Cluster.ts
src/app/shared/ClusterLevel.ts
src/app/shared/CorrelationMatrix.ts
src/app/shared/GaussianCovariate.ts
src/app/shared/HypothesisEffect.ts
src/app/shared/ISUFactor.ts
src/app/shared/ISUFactorCombination.ts
src/app/shared/PartialMatrix.ts
src/app/shared/ci-guard.service.ts
src/app/shared/cluster-guard.service.ts
src/app/shared/gaussian-covariate-guard.service.ts
src/app/study-form/hypothesis-within/hypothesis-within.component.ts
src/app/study-form/parameters-marginal-means/parameters-marginal-means.component.html

Ver3 282 update code docs

---

package.json
src/app/shared/PartialMatrix.ts
src/app/study-form/hypothesis-within/hypothesis-within.component.ts

add mathjs kron back now that npm has updated the types library

VER3-282 add mathjs kron back now that npm has updated the types library

---

src/app/shared/constants.ts
src/app/shared/noduplicates.validator.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.ts

remove ability to add duplicated repeated measure values

Ver3 313 repeatedmeasuresbug

---

src/app/shared/constants.ts
src/app/shared/study-design.ts
src/app/study-form/solve-for/solve-for.component.html
src/app/study-form/solve-for/solve-for.component.spec.ts
src/app/study-form/solve-for/solve-for.component.ts
src/app/study-form/study-form.component.ts
src/app/study-form/study.service.ts

VER3-366 remove sample size field

---

src/app/shared/ISUFactors.ts

added marginal means and ISU Factors

VER3-382 add marginal means to ISUFactors toJSO

---

src/app/shared/MarginalMeansTable.spec.ts
src/app/shared/MarginalMeansTable.ts
src/app/shared/OutcomeRepMeasStDev.ts
src/app/shared/study-design.ts
src/app/study-form/calculate/calculate.component.html
src/app/study-form/calculate/calculate.component.spec.ts
src/app/study-form/parameters-marginal-means/parameters-marginal-means.component.html
src/app/study-form/parameters-marginal-means/parameters-marginal-means.component.ts
src/app/study-form/study-form.component.html

Ver3 382 serialise

---

src/app/shared/constants.ts
src/app/study-form/between-isu-smallest-group/between-isu-smallest-group.component.html
src/app/study-form/between-isu-smallest-group/between-isu-smallest-group.component.spec.ts
src/app/study-form/between-isu-smallest-group/between-isu-smallest-group.component.ts
src/app/study-form/solve-for/solve-for.component.spec.ts

Add validator for small group size.

Ver3 389 form valid for between isu smallest group size

---

src/app/shared/constants.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.ts

Finished adding validators for WITHIN_ISU_REPEATED_MEASURES.

VER3-357 Added validation to WITHIN_ISU_REPEATED_MEASURES.

---

src/app/shared/constants.ts
src/app/study-form/within-isu-clusters/cluster.validator.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.component.html
src/app/study-form/within-isu-clusters/within-isu-clusters.component.ts

Added validation to WITHIN_ISU_CLUSTERS. Including checking min/max, required and duplicated.

VER3-357 Added validation to WITHIN_ISU_CLUSTERS.

---

src/app/shared/constants.ts
src/app/study-form/between-isu-predictors/between-isu-predictors.component.html
src/app/study-form/between-isu-predictors/between-isu-predictors.component.ts

Added validation message to BETWEEN_ISU_PREDICTORS. All test cases passed. Thank you for your reviewing.

VER3-357 Added validation to BETWEEN_ISU_PREDICTORS.

---

src/app/shared/constants.ts
src/app/study-form/between-isu-predictors/between-isu-predictors.component.html
src/app/study-form/between-isu-predictors/between-isu-predictors.component.ts
src/app/study-form/between-isu-predictors/group.validator.ts
src/app/study-form/between-isu-smallest-group/between-isu-smallest-group.component.ts
src/app/study-form/gaussian-covariate/gaussian-covariate.component.html
src/app/study-form/gaussian-covariate/gaussian-covariate.component.ts
src/app/study-form/parameters-scale-factor/parameters-scale-factor.component.html
src/app/study-form/parameters-scale-factor/parameters-scale-factor.component.ts

Added validations to components BETWEEN_ISU_SMALLEST_GROUP, GAUSSIAN_COVARIATE and PARAMETERS_SCALE_FACTOR. All test cases passed. Thanks! Alasdair.

Ver3 357 validator for some components

---

src/app/study-form/hypothesis-effect-choice/hypothesis-effect-choice.component.spec.ts

e2e test for hypothesis effect choice table.
The order test cases include:
1 Between 1 Within
3 Between
3 Within
2 Between 2 Within
3 Between 1 Within
1 Between 3 Within

Ver3 413 e2e test for hypothesis effect choice table

---

src/app/study-form/calculate/calculate.component.html

VER3-401 Show warning messages if necessary.

---

src/app/study-form/calculate/calculate.component.html
src/app/study-form/calculate/calculate.component.ts

Display red message if it is a warning message and green for results.

VER3-401 Improve the CSS of warning message.

---

src/app/study-form/correlation-matrix/correlation-matrix.component.html
src/app/study-form/gaussian-covariate/gaussian-covariate.component.html
src/app/study-form/optional-specs-power-method/optional-specs-power-method.component.html
src/app/study-form/parameters-gaussian-covariate-correlation/parameters-gaussian-covariate-correlation.component.html
src/app/study-form/parameters-marginal-means/parameters-marginal-means.component.html
src/app/study-form/parameters-scale-factor/parameters-scale-factor.component.html
src/app/study-form/parameters-standard-deviation/parameters-standard-deviation.component.html
src/app/study-form/parameters-variance-scale-factors/parameters-variance-scale-factors.component.html
src/app/study-form/within-isu-outcomes/within-isu-outcomes.component.html

Copied the descriptions from V2 to V3. 
After arguing with Qian, still 4 components, HYPOTHESIS_BETWEEN, HYPOTHESIS_WITHIN, HYPOTHESIS_THETA_0, and PARAMETERS_REPEATED_MEASURE_ST_DEV, do not have the corresponding component in V2. I believe they are new features in V3. All test cases passed.
Alasdair, thank you for your reviewing!

Ver3 399 copy descriptions from v2 to v3

---

src/app/study-form/between-isu-predictors/between-isu-predictors.component.html
src/app/study-form/calculate/calculate.component.html
src/app/study-form/calculate/calculate.component.ts
src/app/study-form/within-isu-outcomes/within-isu-outcomes.component.html
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/environments/environment.ts

Ver3 292 styling fixes

---

src/app/shared/constants.ts
src/app/shared/navigation.service.ts
src/app/study-form/study-form-routing.module.ts
src/app/study-form/study-form.component.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.component.html
src/app/study-form/within-isu-clusters/within-isu-clusters.component.spec.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.component.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.po.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.html

brought cluster component in line with style of other isu factor components
finally remove child component nav

Ver3 444 clusters reactor

---

src/app/shared/study-design.ts
src/app/study-form/study-form.component.spec.ts

Ver3 457 beta options

---

src/app/study-form/within-isu-outcomes/within-isu-outcomes.component.html
src/app/study-form/within-isu-outcomes/within-isu-outcomes.component.spec.ts
src/app/study-form/within-isu-outcomes/within-isu-outcomes.component.ts

VER3-454 Add help text modal to the component WITHIN_ISU_OUTCOMES. All test cases pass.

VER3-454 Add help text modal to the component WITHIN_ISU_OUTCOMES.

---

src/app/study-form/within-isu-clusters/within-isu-clusters.component.html
src/app/study-form/within-isu-clusters/within-isu-clusters.component.spec.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.component.ts

VER3-454 Add help text modal to the component WITHIN_ISU_CLUSTERS.

---

src/app/study-form/hypothesis-theta-0/hypothesis-theta-0.component.html
src/app/study-form/hypothesis-theta-0/hypothesis-theta-0.component.spec.ts
src/app/study-form/hypothesis-theta-0/hypothesis-theta-0.component.ts
src/app/study-form/hypothesis-within/hypothesis-within.component.html
src/app/study-form/hypothesis-within/hypothesis-within.component.spec.ts
src/app/study-form/hypothesis-within/hypothesis-within.component.ts

Ver3 454 help text modal hypothesis theta 0

---

src/app/study-form/hypothesis-within/hypothesis-within.component.html
src/app/study-form/hypothesis-within/hypothesis-within.component.spec.ts
src/app/study-form/hypothesis-within/hypothesis-within.component.ts

Ver3 454 help text modal

---

src/app/study-form/parameters-marginal-means/parameters-marginal-means.component.html
src/app/study-form/parameters-marginal-means/parameters-marginal-means.component.ts

VER3-454 Add help text modal to the component PARAMETERS_MARGINAL_MEANS.

---

src/app/study-form/parameters-scale-factor/parameters-scale-factor.component.html
src/app/study-form/parameters-scale-factor/parameters-scale-factor.component.spec.ts
src/app/study-form/parameters-scale-factor/parameters-scale-factor.component.ts

VER3-454 Add help text modal to the component PARAMETERS_SCALE_FACTOR.

---

src/app/study-form/correlation-matrix/correlation-matrix.component.html
src/app/study-form/correlation-matrix/correlation-matrix.component.spec.ts
src/app/study-form/correlation-matrix/correlation-matrix.component.ts

add option for lear corellation matrices

Ver3 193 lear

---

src/app/app.component.html
src/app/study-form/between-isu-groups/between-isu-groups.component.html
src/app/study-form/between-isu-predictors/between-isu-predictors.component.html
src/app/study-form/calculate/calculate.component.html
src/app/study-form/parameters-intra-class-correlation/parameters-intra-class-correlation.component.html
src/app/study-form/parameters-marginal-means/parameters-marginal-means.component.html
src/app/study-form/solve-for/solve-for.component.html
src/app/study-form/study-form.component.html
src/app/study-form/type-one-error/type-one-error.component.html
src/styles.scss

Ver3 463 div overlay

---

src/app/study-form/calculate/calculate.component.ts

fix result disply when we have errors

Ver3 465 test type bug

---

src/app/shared/constants.ts
src/app/study-form/type-one-error/type-one-error.component.ts
src/app/study-form/type-one-error/type-one-error.validator.ts

Ver3 467 type i err validation

---

src/app/shared/navigation.service.ts
src/app/study-form/study-form.component.ts
src/app/study-form/type-one-error/type-one-error.component.ts
src/app/study-form/type-one-error/type-one-error.validator.ts

All tests pass.
I pass the isClickNext parameter by reference to the validator since the validator cannot detect the change of the parameter called by value. For example, if I directly pass the isClickNext(boolean) to the validator, it will always have the initial value. This is really tricky so I will keep figuring out how to do this in a better way.

VER3-476 Only show error message if users click next.

---

e2e/study-form.e2e-spec.ts
src/app/study-form/calculate/calculate.component.html
src/app/study-form/calculate/calculate.po.ts
src/app/study-form/study-form.po.ts

I only finish getting power from the result table now. I want to make sure I am in the right direction before I get other values from the table.

VER3-479 Get power from table for e2e test.

---

e2e/study-form.e2e-spec.ts
src/app/study-form/calculate/calculate.component.html
src/app/study-form/calculate/calculate.po.ts
src/app/study-form/study-form.po.ts
src/environments/environment.ts

I accidentally pushed the environment file. Already reverted it. Sorry for this.

Ver3 479 add samplesize results table based on v2

---

src/app/shared/constants.ts
src/app/shared/navigation.service.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.validator.ts

Only implement this feature to the dimension step in repeated measure component. Will implement this feature to the rest of the component after your confirmation.

VER3-484 Only show warning when user click next.

---

src/app/shared/constants.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.validator.ts

VER3-484 Only show warning when user click next from REPEATS to SPACING.

---

src/app/app.component.html
src/app/mathjax/mathjax.component.html
src/app/study-form/between-isu-predictors/between-isu-predictors.component.css
src/app/study-form/calculate/calculate.component.html
src/app/study-form/gaussian-covariate/gaussian-covariate.component.html
src/app/study-form/parameters-standard-deviation/parameters-standard-deviation.component.html
src/app/study-form/study-form.component.html
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.html
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.scss
src/styles.scss

and other updates to styling for small screens

Ver3 487 overflow styling

---

e2e/study-form.e2e-spec.ts
e2e/test_inputs/MultipleOutcomeSampleSize.ts
e2e/test_inputs/O2R2P2C0_output.ts
e2e/test_inputs/SampleSizeOneSampleTTest.ts
e2e/test_inputs/detail_table.ts
e2e/test_inputs/example_1_input.ts
e2e/test_inputs/generic_test_data_model.ts
e2e/test_inputs/homework2_longitudinal.ts
e2e/test_inputs/homework3.ts
e2e/test_inputs/homework4.ts
e2e/test_inputs/homework5.ts
e2e/test_inputs/homework5_fullbeta.ts
src/app/study-form/hypothesis-between/hypothesis-between.component.ts
src/app/study-form/hypothesis-theta-0/hypothesis-theta-0.component.html
src/app/study-form/hypothesis-theta-0/hypothesis-theta0.po.ts
src/app/study-form/hypothesis-within/hypothesis-within.component.ts
src/app/study-form/parameters-marginal-means/parameters-marginal-means.po.ts
src/app/study-form/solve-for/solve-for.component.html
src/app/study-form/solve-for/solve-for.po.ts
src/app/study-form/type-one-error/type-one-error.component.html
src/app/study-form/type-one-error/type-one-error.component.scss
src/app/study-form/type-one-error/type-one-error.po.ts
src/app/study-form/within-isu-outcomes/within-isu-outcomes.component.html
src/styles.scss

1. OneSample T Test
2. Multiple outcomes

VER3-273 Testing Sample Size calculation

---

e2e/study-form.e2e-spec.ts
e2e/test_inputs/CI_input_1.ts
e2e/test_inputs/CI_input_2.ts
src/app/study-form/custom-contrast-matrix/custom-contrast-matrix.component.spec.ts
src/app/study-form/optional-specs-confidence-intervals/optional-specs-confidence-intervals.po.ts

e2e test completed for confidence interval

Ver3 520 e2e test ci

---

src/app/study-form/between-isu-predictors/between-isu-predictors.component.html
src/app/study-form/between-isu-predictors/between-isu-predictors.component.ts
src/app/study-form/within-isu-repeated-measures/within-isu-repeated-measures.component.ts
src/environments/environment.ts

fix repeated measure form updates

Ver3 526 spacing

---

src/app/study-form/between-isu-smallest-group/between-isu-smallest-group.component.html
src/app/study-form/hypothesis-theta-0/hypothesis-theta-0.component.html
src/app/study-form/parameters-gaussian-covariate-correlation/parameters-gaussian-covariate-correlation.component.html
src/app/study-form/parameters-gaussian-covariate-correlation/parameters-gaussian-covariate-correlation.component.ts
src/app/study-form/parameters-repeated-measure-stdev/parameters-repeated-measure-stdev.component.html

Descriptive text and default value updates

Ver3 495 hypothesis descriptions

---

src/app/shared/constants.ts
src/app/study-form/within-isu-clusters/cluster.validator.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.component.html
src/app/study-form/within-isu-clusters/within-isu-clusters.component.spec.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.component.ts
src/app/study-form/within-isu-clusters/within-isu-clusters.po.ts

update cluster page language, validators and descriptions

Ver3 540 cluster description

---

src/app/study-form/status/status.component.html
src/environments/environment.ts

Ver3 543 status

---

e2e/study-form.e2e-spec.ts
e2e/test_inputs/GLMM(F)_example7.ts
e2e/test_inputs/POWERLIB_Example_5.ts
e2e/test_inputs/POWERLIB_Example_7.ts

added more E2E tests from examples

Ver3 553 more e2e part2
